### ISSUE TITLE
What are the available parameters for generator?

### ISSUE THREAD

**Issue by sungkim11** [declare-lab/flan-alpaca#1]
What are the available parameters for generator? I see that temperature needs to be a float, but I am not aware of other:

generator = pipeline(model="declare-lab/flan-alpaca-xl")
generated_text = generator(prompt, temperature=0.1, max_length=784, do_sample=False)

**Comment by chiayewken** [comment]
Hi, the parameters are the same for most other hugging face generation models and the details can be found here:

https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationConfig
