### ISSUE TITLE
wget https://raw.githubusercontent.com/tloen/alpaca-lora/main/alpaca_data_cleaned.json -O data/alpaca_clean.json

### ISSUE THREAD

**Issue by kizombaciao** [declare-lab/flan-alpaca#15]
I received the below error.  It seems this error means that the specified URL "https://raw.githubusercontent.com/tloen/alpaca-lora/main/alpaca_data_cleaned.json" returned a 404 Not Found HTTP response code, indicating that the requested resource was not found on the server.

This error could occur for several reasons, including:

The URL may be incorrect or outdated, and the resource may have been moved or deleted.
The server hosting the resource may be down or inaccessible.
The resource may have been intentionally removed or blocked.
In this case, it seems that the alpaca_data_cleaned.json file could not be found at the specified location. You may want to check if the file exists at the URL or if the URL has changed.

The file alpaca_data_cleaned.json seems to be no longer available.
---

wget https://raw.githubusercontent.com/tloen/alpaca-lora/main/alpaca_data_cleaned.json -O data/alpaca_clean.json
--2023-04-10 09:39:10--  https://raw.githubusercontent.com/tloen/alpaca-lora/main/alpaca_data_cleaned.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-10 09:39:11 ERROR 404: Not Found.

**Comment by sfxworks** [comment]
https://github.com/declare-lab/flan-alpaca/pull/14
Use `wget https://raw.githubusercontent.com/tloen/alpaca-lora/main/alpaca_data_cleaned_archive.json -O data/alpaca_clean.json`

**Comment by chiayewken** [comment]
Hi, the data links are fixed now, we are hosting the datasets in the [release](https://github.com/declare-lab/flan-alpaca/releases/tag/v0.1.0) to avoid future broken links in external repos

The download commands are updated in the [readme](https://github.com/declare-lab/flan-alpaca#setup)

**Comment by kizombaciao** [comment]
Thanks for the rapid response!
