### ISSUE TITLE
Quantized

### ISSUE THREAD

**Issue by naturallydeer** [declare-lab/flan-alpaca#2]
First off, this model is pretty good and I'm enjoying it almost as much as ChatGPT.

Would like to ask if it is possible to quantize the model using Optimum? The following code throws me an Onnx Error.

[ONNXRuntimeError] : 1 : FAIL : Deserialize tensor onnx::MatMul_5230 failed.tensorprotoutils.cc:640 onnxruntime::utils::TensorProtoToTensor External initializer: onnx::MatMul_5230 offset: 0 size to read: 41943040 given file_length: 16777216 are out of bounds or can not be read in full.

```
model_id="declare-lab/flan-alpaca-xl"
model = ORTModelForSeq2SeqLM.from_pretrained(model_id, from_transformers=True)
```

Thank you!

**Comment by GarciaLnk** [comment]
Exporting to ONNX and quantizing worked fine for me using Optimum. You can simply use optimum-cli like this:

```
optimum-cli export onnx --model declare-lab/flan-alpaca-base flan-alpaca-base_onnx/
optimum-cli onnxruntime quantize --onnx_model flan-alpaca-base_onnx/ --avx2
```

But keep in mind that by default only MatMul and Add operators are quantized, you need to pass a custom config if you want all the operators to be quantized. You can find the base model exported and fully quantized in my HF repo: https://huggingface.co/GarciaLnk/onnx-models-quantized/tree/main/flan-alpaca-base
