### ISSUE TITLE
Trouble training

### ISSUE THREAD

**Issue by KurtFeynmanGodel** [declare-lab/flan-alpaca#5]
Having trouble running your training script. I haven't looked into debugging the code but I assumed it works with the alpaca dataset as is. Should the alpaca json file be preprocessed in some way before running the training script?

File "/home/voiduser/pydev/flan-alpaca/flan-alpaca/data_loading.py", line 45, in <listcomp>
    samples = [TextToTextSample(**json.loads(line)) for line in f]
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

**Comment by chiayewken** [comment]
Hi, that's strange, I tried the data loading from scratch and could not reproduce your issue. Can I check if you are following the setup and data preprocessing steps here? Also, can you show the command that caused the error?

https://github.com/declare-lab/flan-alpaca#setup
