### ISSUE TITLE
use gpt4all dataset

### ISSUE THREAD

**Issue by Shiro836** [declare-lab/flan-alpaca#7]
I am impressed by the quality results and speed of the XL model. And it can very easily fit in my 24GB GPU.
I found this dataset recently: https://github.com/nomic-ai/gpt4all But my GPU is unable to train the model due to insufficient memory. Can anyone train it, please?

**Comment by Shiro836** [comment]
Awesome!!! The results are insanely good.

**Comment by munish0838** [comment]
Hi @Shiro836, can you please share the training process!
