### ISSUE TITLE
issue in training declare-lab/flan-alpaca-base model

### ISSUE THREAD

**Issue by p1yush99** [declare-lab/flan-alpaca#8]
Hi,
im able to train google/flan-t5-base or large models on my data after tweaking the training code for bfloat as my gpu does not support it, but i want to train declare-lab/flan-alpaca-base model on my data this time, its throwing long error message 

` File "/home/ec2-user/SageMaker/conda_envs/llm/lib/python3.8/site-packages/triton/language/semantic.py", line 633, in bitcast
    raise ValueError("Cannot bitcast data-type of size " + str(src_bits) + "to "
ValueError: Cannot bitcast data-type of size 64to data-type of size 32`

can anyone suggest anything on it?

**Comment by chiayewken** [comment]
Hi, it may be a torch.compile issue based on this discussion: https://github.com/pytorch/pytorch/issues/98186

Could you try removing "--use_compile" in your training command and try?
If you need to save more memory, you can add "--use_gradient_checkpointing" to your training command instead

**Comment by p1yush99** [comment]
thanks, it worked, later it gave cuda out of memory error, so i had to reduce batch size to 8 (earlier it was 32) for training. But its training really slow, GPU is tesla v100
